FROM python:3.8-slim-buster

WORKDIR /opt/code

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV APP_USER=costa

RUN groupadd -r ${APP_USER} && useradd --create-home -g ${APP_USER} ${APP_USER}

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt \
    && rm -rf /var/lib/apt/lists/*

USER ${APP_USER}

COPY --chown=${APP_USER}:${APP_USER} . .
